[buildPlans.IosevkaZan]
family = "IosevkaZan"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaZan.variants.design]
one = "no-base-long-top-serif"
three = "two-arcs"
four = "closed-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "tall-slashed"
capital-a = "curly-serifless"
capital-c = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "short-serifed"
capital-j = "flat-hook-serifless"
capital-k = "curly-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
a = "double-storey-tailed"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
i = "serifless"
j = "flat-hook-serifless"
k = "curly-serifless"
l = "serifless"
m = "earless-single-arch-serifless"
n = "straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "hookless-serifless"
t = "flat-hook"
u = "toothed-serifless"
y = "straight-serifless"
capital-eszet = "corner-serifless"
eszet = "traditional-serifless"
capital-delta = "curly"
lower-delta = "flat-top"
lower-lambda = "curly-tailed-turn"
lower-pi = "tailless"
cyrl-a = "double-storey-serifless"
cyrl-ve = "standard-interrupted-serifless"
cyrl-ka = "curly-serifless"
cyrl-em = "hanging-serifless"
cyrl-er = "earless-rounded-serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "penta-high"
underscore = "low"
caret = "high"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-tall"
ampersand = "upper-open"
at = "fourfold-solid-inner-tall"
dollar = "interrupted"
percent = "dots"
question = "smooth"
pilcrow = "low"
lig-neq = "vertical-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaZan.ligations]
  inherits = "dlig"

[buildPlans.IosevkaZan.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IosevkaZan.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaZan.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaZan.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaZan.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaZan.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
