name: PR Font Build Validation

on: push

jobs:
  build:
    name: Build ${{ matrix.fontName }} font
    if: github.repository == 'AgatZan/IosevkaZan'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fontName: ["IosevkaZan"]

    steps:
      # Checkout repository into `iosevka` sub directory
      - uses: actions/checkout@v4
        with:
          path: iosevka

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttf::${{ matrix.fontName }}
      - name: List files
        working-directory: iosevka
        run: ls -la
      - name: Zip
        shell: bash
        working-directory: iosevka
        run: |
          zip -r IosevkaZan.zip iosevka/dist/IosevkaZan/TTF/
      - name: List files
        working-directory: iosevka
        run: ls -la
      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: IosevkaZan
          path: |
            iosevka/IosevkaZan.zip
        # uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        # with:
        #   files: |
        #     IosevkaZan.zip
            
