name: PR Font Build Validation

on: push

jobs:
  build:
    name: Build ${{ matrix.fontName }} font
    if: github.repository == 'AgatZan/IosevkaZan'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fontName: ["IosevkaZan"]

    steps:
      # Checkout repository into `iosevka` sub directory
      - uses: actions/checkout@v4
        with:
          path: iosevka

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font ${{ matrix.fontName }}
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttf::${{ matrix.fontName }}
          echo ${{ github.sha }} > Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
            dist/IosevkaZan/TTF/IosevkaZan-ExtraLight.ttf
            dist/IosevkaZan/TTF/IosevkaZan-ExtraLightOblique.ttf
            dist/IosevkaZan/TTF/IosevkaZan-ExtraLightItalic.ttf
            dist/IosevkaZan/TTF/IosevkaZan-Regular.ttf
            dist/IosevkaZan/TTF/IosevkaZan-Oblique.ttf
            dist/IosevkaZan/TTF/IosevkaZan-Italic.ttf
            dist/IosevkaZan/TTF/IosevkaZan-Bold.ttf
            dist/IosevkaZan/TTF/IosevkaZan-BoldOblique.ttf
            dist/IosevkaZan/TTF/IosevkaZan-BoldItalic.ttf
            
      
